"""empty message

Revision ID: 105c376804
Revises: 24bab9e400e
Create Date: 2015-04-16 08:13:52.062867

"""

# revision identifiers, used by Alembic.
revision = '105c376804'
down_revision = '24bab9e400e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'site',
        sa.Column('url', sa.String(length=512), nullable=True))

    site = sa.sql.table(
        'site',
        sa.sql.column('domain', sa.String),
        sa.sql.column('url', sa.String))

    op.execute(
        site.update().values(url=sa.func.concat('http://', site.c.domain)))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site', 'url')
    ### end Alembic commands ###
