"""empty message

Revision ID: 24bab9e400e
Revises: None
Create Date: 2015-04-16 08:09:05.502063

"""

# revision identifiers, used by Alembic.
revision = '24bab9e400e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
