"""add refresh token column to account

Revision ID: 3281edf1d68
Revises: 105c376804
Create Date: 2015-07-27 19:50:30.687346

"""

# revision identifiers, used by Alembic.
revision = '3281edf1d68'
down_revision = '105c376804'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('o_auth_request_token')
    op.add_column('account', sa.Column('refresh_token', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'refresh_token')
    op.create_table('o_auth_request_token',
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('token_secret', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('token', name='o_auth_request_token_pkey')
    )
    ### end Alembic commands ###
